[[http]]
  display_name = "url地址重写"
  sort = 6
  postion = "normal"
  unique_name = "url_rewrite"

  [[http.items]]
    field_type = "textarea"
    field_display = "block"
    field_clear = "none"
    field_placeholder = "格式：^/gateway/test_service(.*) $1 多条换行"
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "rewrite_rule"
    field_display_name = "URL重写"
    field_required = false
    field_valid_rule = "/[\\S]+/"

[[http]]
  display_name = "限流中间件"
  sort = 3
  postion = "normal"
  unique_name = "http_flow_limit"

  [[http.items]]
    field_type = "input"
    field_display = "inline"
    field_clear = "left"
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = "0"
    field_unique_name = "service_flow_limit_num"
    field_display_name = "服务限流数"
    field_required = true
    field_valid_rule = "/[0-9]/"

  [[http.items]]
    field_type = "select"
    field_display = "inline"
    field_clear = "right"
    field_placeholder = ""
    field_option = "0|1|2,秒|分|时"
    field_value = ""
    field_default_value = "0"
    field_unique_name = "service_flow_limit_type"
    field_display_name = "服务限流类型"
    field_required = false
    field_valid_rule = ""

  [[http.items]]
    field_type = "input"
    field_display = "inline"
    field_clear = "left"
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = "0"
    field_unique_name = "clientip_flow_limit_num"
    field_display_name = "客户IP限流数"
    field_required = true
    field_valid_rule = "/[0-9]/"

  [[http.items]]
    field_type = "select"
    field_display = "inline"
    field_clear = "right"
    field_placeholder = ""
    field_option = "0|1|2,秒|分|时"
    field_value = ""
    field_default_value = "0"
    field_unique_name = "clientip_flow_limit_type"
    field_display_name = "客户IP限流类型"
    field_required = false
    field_valid_rule = ""

[[http]]
  display_name = "Header头转换"
  sort = 3
  postion = "normal"
  unique_name = "header_transfer"

  [[http.items]]
    field_type = "textarea"
    field_display = "inline"
    field_clear = "none"
    field_placeholder = "header转换支持 add(增加)/del(删除)/edit(修改) 格式：add headerName headValue"
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "transfer_rule"
    field_display_name = "header转换"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

[[http]]
  display_name = "白名单 & 黑名单 & host白名单 & url白名单"
  sort = 2
  postion = "normal"
  unique_name = "http_whiteblacklist"

  [[http.items]]
    field_type = "textarea"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "ip_white_list"
    field_display_name = "IP白名单"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

  [[http.items]]
    field_type = "textarea"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "ip_black_list"
    field_display_name = "IP黑名单"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

  [[http.items]]
    field_type = "input"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "host_white_list"
    field_display_name = "HOST白名单"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

  [[http.items]]
    field_type = "input"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "url_white_list"
    field_display_name = "URL白名单"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

[[http]]
  display_name = "连接池设置"
  sort = 2
  postion = "normal"
  unique_name = "http_upstream_transport"

  [[http.items]]
    field_type = "input"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "http_upstream_connection_timeout"
    field_display_name = "下游连接超时时间"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

  [[http.items]]
    field_type = "input"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "http_upstream_header_timeout"
    field_display_name = "下游响应超时时间"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

[[http]]
  display_name = "jwt验证"
  sort = 2
  postion = "auth"
  unique_name = "jwt_auth"

[[http]]
  display_name = "默认后端配置"
  sort = 2
  postion = "loadbalance"
  unique_name = "upstream_config"

  [[http.items]]
    field_type = "textarea"
    field_display = ""
    field_clear = ""
    field_placeholder = "每个规则一行 如：http://127.0.0.1:8701 100"
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "upstream_list"
    field_display_name = "下游服务器ip+权重"
    field_required = false
    field_valid_rule = "/[\\S]+ [\\S]+/"

[[tcp]]
  display_name = "限流中间件"
  sort = 3
  postion = "normal"
  unique_name = "tcp_flow_limit"

  [[tcp.items]]
    field_type = "input"
    field_display = "inline"
    field_clear = "none"
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = "0"
    field_unique_name = "service_flow_limit_num"
    field_display_name = "服务限流数"
    field_required = false
    field_valid_rule = "/^[0-9]$/"

  [[tcp.items]]
    field_type = "select"
    field_display = "inline"
    field_clear = "right"
    field_placeholder = ""
    field_option = "0|1|2,秒|分|时"
    field_value = ""
    field_default_value = "0"
    field_unique_name = "service_flow_limit_type"
    field_display_name = "服务限流类型"
    field_required = false
    field_valid_rule = "/^[0-9]$/"

  [[tcp.items]]
    field_type = "input"
    field_display = "inline"
    field_clear = "none"
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = "0"
    field_unique_name = "clientip_flow_limit_num"
    field_display_name = "客户IP限流数"
    field_required = false
    field_valid_rule = "/^[0-9]$/"

  [[tcp.items]]
    field_type = "select"
    field_display = "inline"
    field_clear = "right"
    field_placeholder = ""
    field_option = "0|1|2,秒|分|时"
    field_value = ""
    field_default_value = "0"
    field_unique_name = "clientip_flow_limit_type"
    field_display_name = "客户IP限流类型"
    field_required = false
    field_valid_rule = "/^[0-9]$/"

[[tcp]]
  display_name = "白名单 & 黑名单 & host白名单"
  sort = 2
  postion = "normal"
  unique_name = "tcp_whiteblacklist"

  [[tcp.items]]
    field_type = "textarea"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "ip_white_list"
    field_display_name = "IP白名单"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

  [[tcp.items]]
    field_type = "textarea"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "ip_black_list"
    field_display_name = "IP黑名单"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

  [[tcp.items]]
    field_type = "input"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "host_white_list"
    field_display_name = "HOST白名单"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

[[tcp]]
  display_name = "默认后端配置"
  sort = 2
  postion = "loadbalance"
  unique_name = "upstream_config"

  [[tcp.items]]
    field_type = "textarea"
    field_display = ""
    field_clear = ""
    field_placeholder = "每个规则一行 如：tcp://127.0.0.1:8701 100"
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "upstream_list"
    field_display_name = "下游服务器ip+权重"
    field_required = false
    field_valid_rule = "/^[\\S]+ [\\S]+$/"

[[grpc]]
  display_name = "限流中间件"
  sort = 3
  postion = "normal"
  unique_name = "grpc_flow_limit"

  [[grpc.items]]
    field_type = "input"
    field_display = "inline"
    field_clear = "none"
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = "0"
    field_unique_name = "service_flow_limit_num"
    field_display_name = "服务限流数"
    field_required = false
    field_valid_rule = "^[0-9]$"

  [[grpc.items]]
    field_type = "select"
    field_display = "inline"
    field_clear = "right"
    field_placeholder = ""
    field_option = "0|1|2,秒|分|时"
    field_value = ""
    field_default_value = "0"
    field_unique_name = "service_flow_limit_type"
    field_display_name = "服务限流类型"
    field_required = false
    field_valid_rule = "/^[0-9]$/"

  [[grpc.items]]
    field_type = "input"
    field_display = "inline"
    field_clear = "none"
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = "0"
    field_unique_name = "clientip_flow_limit_num"
    field_display_name = "客户IP限流数"
    field_required = false
    field_valid_rule = "/^[0-9]$/"

  [[grpc.items]]
    field_type = "select"
    field_display = "inline"
    field_clear = "right"
    field_placeholder = ""
    field_option = "0|1|2,秒|分|时"
    field_value = ""
    field_default_value = "0"
    field_unique_name = "clientip_flow_limit_type"
    field_display_name = "客户IP限流类型"
    field_required = false
    field_valid_rule = "/^[0-9]$/"

[[grpc]]
  display_name = "metadata转换"
  sort = 3
  postion = "normal"
  unique_name = "metadata_transfer"

  [[grpc.items]]
    field_type = "textarea"
    field_display = "inline"
    field_clear = "none"
    field_placeholder = "metadata 转换支持 add(增加)/del(删除)/edit(修改) 格式：add headerName headValue"
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "transfer_rule"
    field_display_name = "metadata转换"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

[[grpc]]
  display_name = "白名单 & 黑名单 & host白名单"
  sort = 2
  postion = "normal"
  unique_name = "grpc_whiteblacklist"

  [[grpc.items]]
    field_type = "textarea"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "ip_white_list"
    field_display_name = "IP白名单"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

  [[grpc.items]]
    field_type = "textarea"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "ip_black_list"
    field_display_name = "IP黑名单"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

  [[grpc.items]]
    field_type = "input"
    field_display = ""
    field_clear = ""
    field_placeholder = ""
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "host_white_list"
    field_display_name = "HOST白名单"
    field_required = false
    field_valid_rule = "/^[\\S]+$/"

[[grpc]]
  display_name = "默认后端配置"
  sort = 2
  postion = "loadbalance"
  unique_name = "upstream_config"

  [[grpc.items]]
    field_type = "textarea"
    field_display = ""
    field_clear = ""
    field_placeholder = "每个规则一行 如：grpc://127.0.0.1:8701 100 "
    field_option = ""
    field_value = ""
    field_default_value = ""
    field_unique_name = "upstream_list"
    field_display_name = "下游服务器ip+权重"
    field_required = false
    field_valid_rule = "/^[\\S]+ [\\S]+$/"